#!/bin/sh

#
# tempread
#
# Liefert Temperaturdaten aus den RRD-Dateien als JSON.
#
# Aufrufe:
#
#   /cgi-bin/tempread?list=1
#
# liefert:
#
#   {
#       "sitename":"Temperaturen Bestensee",
#       "graphs":[
#           "Warmwasser",
#           "Solar",
#           "Speicher",
#           "Außentemperatur"
#       ]
#   }
#
#
#   /cgi-bin/tempread?graph=Solar&range=24h
#
# liefert die Messdaten des angegebenen Graphen.
#

echo "Content-Type: application/json"
echo ""

graph=""
range="1h"
list="0"


urldecode()
{
    value="$1"

    value="$(
        printf '%s' "$value" |
        sed 's/+/ /g;s/%/\\x/g'
    )"

    printf '%b' "$value"
}


OLDIFS="$IFS"
IFS='&'

for parameter in $QUERY_STRING
do
    case "$parameter" in
        graph=*)
            graph="$(
                urldecode "${parameter#graph=}"
            )"
            ;;

        range=*)
            range="${parameter#range=}"
            ;;

        list=1)
            list="1"
            ;;
    esac
done

IFS="$OLDIFS"


case "$range" in
    1h)
        start="now-1h"
        ;;

    24h)
        start="now-24h"
        ;;

    7d)
        start="now-7d"
        ;;

    30d)
        start="now-30d"
        ;;

    1y)
        start="now-1y"
        ;;

    *)
        range="1h"
        start="now-1h"
        ;;
esac


rrd_path="$(
    uci -q get mqtt-tempd.@rrd[0].path
)"


json_string()
{
    printf '%s' "$1" |
    sed \
        -e 's/\\/\\\\/g' \
        -e 's/"/\\"/g' \
        -e 's/	/\\t/g'
}


output_sensor()
{
    label="$1"
    file="$2"

    printf '{'

    printf '"name":"'
    json_string "$label"
    printf '",'

    printf '"data":'

    if [ ! -f "$file" ]; then

        printf '[]'

    else

        rrdtool fetch "$file" AVERAGE \
            --start "$start" 2>/dev/null |
        awk '
            BEGIN {
                printf "["
                first = 1
            }

            /^[0-9]+:/ {
                timestamp = $1
                sub(/:$/, "", timestamp)

                value = $2

                if ((value != "nan") &&
                    (value != "-nan")) {

                    if (!first) {
                        printf ","
                    }

                    printf "[%s,%s]",
                           timestamp,
                           value

                    first = 0
                }
            }

            END {
                printf "]"
            }
        '
    fi

    printf '}'
}


output_graph()
{
    wanted_graph="$1"
    count=0

    if [ -z "$rrd_path" ]; then
        printf '"error":"RRD path not configured"'
        return
    fi


    for section in $(
        uci show mqtt-tempd |
        sed -n \
            's/^mqtt-tempd\.\([^=]*\)=sensor$/\1/p'
    )
    do
        graph_name="$(
            uci -q get \
                "mqtt-tempd.$section.graphname"
        )"

        if [ "$graph_name" != "$wanted_graph" ]; then
            continue
        fi


        sensor_name="$(
            uci -q get \
                "mqtt-tempd.$section.name"
        )"

        sensor_label="$(
            uci -q get \
                "mqtt-tempd.$section.label"
        )"


        if [ -z "$sensor_name" ]; then
            continue
        fi


        if [ -z "$sensor_label" ]; then
            sensor_label="$sensor_name"
        fi


        if [ "$count" -gt 0 ]; then
            printf ','
        fi


        printf '"sensor%d":' \
            "$((count + 1))"


        output_sensor \
            "$sensor_label" \
            "$rrd_path/$sensor_name.rrd"


        count="$((count + 1))"


        #
        # Pro Graph werden maximal zwei
        # Sensoren dargestellt.
        #
        if [ "$count" -ge 2 ]; then
            break
        fi
    done


    if [ "$count" -eq 0 ]; then
        printf '"error":"Graph not configured"'
    fi
}


output_list()
{
    sitename="$(
        uci -q get mqtt-tempd.@web[0].sitename
    )"


    if [ -z "$sitename" ]; then
        sitename="Temperaturen"
    fi


    printf '{'

    printf '"sitename":"'
    json_string "$sitename"
    printf '",'

    printf '"graphs":['


    first=1
    graph_list=""


    for section in $(
        uci show mqtt-tempd |
        sed -n \
            's/^mqtt-tempd\.\([^=]*\)=sensor$/\1/p'
    )
    do
        graph_name="$(
            uci -q get \
                "mqtt-tempd.$section.graphname"
        )"


        if [ -z "$graph_name" ]; then
            continue
        fi


        #
        # Bereits ausgegebenen Graphnamen
        # überspringen.
        #
        case "
$graph_list
" in
            *"
$graph_name
"*)
                continue
                ;;
        esac


        graph_list="${graph_list}${graph_name}
"


        if [ "$first" -eq 0 ]; then
            printf ','
        fi


        printf '"'
        json_string "$graph_name"
        printf '"'


        first=0
    done


    printf ']'
    printf '}\n'
}


if [ "$list" = "1" ]; then

    output_list
    exit 0

fi


if [ -z "$graph" ]; then

    printf '{"error":"Graph not specified"}\n'
    exit 0

fi


printf '{'
output_graph "$graph"
printf '}\n'
